name: api-go-rinha-2025-lucas-e-bernardo

services:
  api01: &api
    hostname: api01
    container_name: api01
    image: rinha-2025-api-go
    build:
      context: ../
      target: build
      dockerfile: ./docker/Dockerfile
      args:
         BUILD_WITH_RACE_DETECTION: $BUILD_WITH_RACE_DETECTION
    env_file:
      - ../.env
    environment:
      - START_HEALTH_CHECKER=1

    volumes:
      - ../:/app
    ports:
      - 9901:80
    networks:
      - backend
      - payment-processor
    command: sh -c "if [ \"$WATCH_FILES\" = \"1\" ]; then air; else /usr/local/bin/main; fi"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '115MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    environment:
      - START_HEALTH_CHECKER=0
    ports:
      - '9902:80'

  db:
    image: postgres:17
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha_pay
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0 -c max_connections=200 -c shared_buffers=35MB -c effective_cache_size=105MB -c maintenance_work_mem=8960kB -c checkpoint_completion_target=0.9 -c wal_buffers=1075kB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=300 -c work_mem=89kB -c huge_pages=off -c min_wal_size=1GB -c max_wal_size=4GB
    healthcheck:
      test: "pg_isready --username=admin --dbname=rinha_pay"
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '110MB'

  nginx:
    image: nginx:latest
    container_name: lb
    volumes:
      - ../scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:80'
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '10MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true